name: W1 reutilizável - Adiciona ao texto e Dobra o número
on:
 workflow_call:
  secrets:
   TEXT_IN_SECRET:
    required: true
  inputs:
      text_in:
        description: Texto de entrada
        required: true
        type: string
      number_in:
        description: Número de entrada
        required: true
        type: number
  outputs:
      text_out:
        description: Texto modificado
        value: ${{ jobs.transform.outputs.text_out }}
      number_out:
        description: Número modificado
        value: ${{  jobs.transform.outputs.number_out }}
jobs:
   transform:
     runs-on: ubuntu-latest
     outputs:
        text_out: ${{ steps.calc.outputs.text_out }}
        number_out: ${{ steps.calc.outputs.number_out }}
     steps:
        - id: calc
          shell: bash
          run: |
              echo "text_secret =  $TEXT_IN_SECRET"
              TEXT="${{ inputs.text_in }}"
              NUM=${{ inputs.number_in }}
              NEW_TEXT="${TEXT}-${NUM}"
              NEW_NUM=$(( NUM * 2 ))
              echo "text_out=$NEW_TEXT" >> "$GITHUB_OUTPUT"
              echo "number_out=$NEW_NUM" >> "$GITHUB_OUTPUT"
